// Arduino (C++) code generator for Blockly
import * as Blockly from 'blockly';

// Operator precedence for C++/Arduino — higher number = lower precedence
export const ArduinoOrder = {
  ATOMIC: 0,
  UNARY_POSTFIX: 1,
  UNARY_PREFIX: 2,
  MULTIPLICATIVE: 3,
  ADDITIVE: 4,
  SHIFT: 5,
  RELATIONAL: 6,
  EQUALITY: 7,
  BITWISE_AND: 8,
  BITWISE_XOR: 9,
  BITWISE_OR: 10,
  LOGICAL_AND: 11,
  LOGICAL_OR: 12,
  CONDITIONAL: 13,
  ASSIGNMENT: 14,
  NONE: 99,
};

export const arduinoGenerator = new Blockly.Generator('Arduino');

arduinoGenerator.INDENT = '  ';
arduinoGenerator.ORDER_OVERRIDES = [];

arduinoGenerator.init = function (workspace) {
  this.definitions_ = Object.create(null);
  if (!this.nameDB_) {
    this.nameDB_ = new Blockly.Names('');
  }
  this.nameDB_.reset();
};

arduinoGenerator.finish = function (code) {
  const includes = [];
  const globals = [];

  for (const val of Object.values(this.definitions_)) {
    const firstLine = val.split('\n')[0].trim();
    if (firstLine.startsWith('#include') || firstLine.startsWith('#define')) {
      if (!includes.includes(val)) includes.push(val);
    } else {
      globals.push(val);
    }
  }

  const headerParts = ['// Auto-generated by TechyGuide', '#include <Arduino.h>'];
  if (includes.length) headerParts.push(...includes);
  if (globals.length) headerParts.push('', ...globals);

  return headerParts.join('\n') + '\n\n' + code;
};

arduinoGenerator.scrub_ = function (block, code, thisOnly) {
  const nextBlock = block.nextConnection?.targetBlock();
  if (nextBlock && !thisOnly) {
    return code + this.blockToCode(nextBlock);
  }
  return code;
};
